-- Сущность options
CREATE TABLE IF NOT EXISTS claramente_option_tabs (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    SORT INT NOT NULL DEFAULT 100,
    CONSTRAINT CODE_UNIQUE UNIQUE (CODE)
);

-- Сущность tabs
CREATE TABLE IF NOT EXISTS claramente_options (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    VALUE TEXT,
    SORT INT NOT NULL DEFAULT 100,
    TAB_ID INT,
    TYPE VARCHAR(255) NOT NULL,
    SITE_ID VARCHAR(12),
    SETTINGS TEXT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CODE_SITE_ID_UNIQUE UNIQUE (CODE, SITE_ID),
    CONSTRAINT CODE_FK FOREIGN KEY (CODE) REFERENCES claramente_option_tabs(CODE),
    CONSTRAINT TAB_ID_FK FOREIGN KEY (TAB_ID) REFERENCES claramente_option_tabs(ID) ON DELETE SET NULL
    );

--  Обновление 1.0.1 от 2025-02-18
ALTER TABLE claramente_options ADD COLUMN IF NOT EXISTS IS_ADMIN_ONLY SMALLINT NOT NULL DEFAULT 0;